dist/src/main/resources/hawkular-welcome-content/hawkular.css
dist/src/main/resources/hawkular-welcome-content/index.html
dist/src/main/resources/hawkular-welcome-content/index_noconsole.html
dist/src/main/resources/hawkular-welcome-content/noconsole.html
dist/src/main/resources/hawkular-welcome-content/noredirect.html

The status for alerts will fail until https://issues.jboss.org/browse/HWKALERTS-148 is fixed

Add status check on the front page

---

pom.xml

@jpkrohling Merge at your leisure.

Alerting 1.1.0.Final -> 1.1.1.Final

---

dist/src/main/resources/hawkular-welcome-content/hawkular.css
dist/src/main/resources/hawkular-welcome-content/index.html

+ some minor layout improvements (using table to have the versions and statuses aligned)

Adding the link to the agent installer to the splash screen 

---

itest/src/test/java/org/hawkular/services/rest/test/InventoryITest.java
pom.xml

Doing these two commits as a single PR so that we see the two coming together in a green build.

Inventory 0.17.2.final + Agent 0.20.0.final

---

pom.xml

Bump metrics to v 0.17.0

---

hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/bus/CommandEventListener.java

Enhance the CommandEventListener to handle a Undeploy responses
as well as datasource responses. Note that DS messages are a future,
so support is written in anticipation.

Hawkular-1107 Add more event types

---

itest/src/test/java/org/hawkular/services/rest/test/AgentITest.java

Remove deprecated inventory api from AgentITest

---

itest/src/test/java/org/hawkular/services/rest/test/AgentITest.java

@theute , @jmazzitelli , could one of you please review this one? If this passes on Torii as well, I'll make a Services release afterwards.

HAWKULAR-1112 - Increased number of retries on itests

---

.travis.hawkular-client.ruby.sh
.travis.yml

Fixing github call for bot.

---

hawkular-rest/pom.xml

Sync version of hystrix-metrics-event-stream with hystrix-core

---

pom.xml

moves to the next agent release

upgrade to latest agent

---

pom.xml

This fixes an issue with the websocket not re-connecting reliably

Bump agent to 0.24.3

---

docker-dist/src/main/docker/docker-assembly.xml
feature-pack/feature-pack-build.xml
feature-pack/pom.xml
pom.xml

do not merge until https://github.com/hawkular/hawkular-agent/pull/280 gets into the agent master branch

support agent extension for EAP6

---

hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/bus/CommandEventListener.java
hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/bus/InventoryEventListener.java
hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/bus/ListenerUtils.java

Listen for Inventory events creating or removing servers. Note there
are several server resource types, WildFly Server, Host Controller,
etc...
Refactored a bit now that we have different sorts of inventory
events generating server-side work and multiple listeners generating
Events for MIQ consumption.

HAWKULAR-1188 Event on Server addition or removal

---

feature-pack/feature-pack-build.xml
feature-pack/pom.xml
feature-pack/src/main/xsl/subsystem-templates/hawkular-services-infinispan.xsl
pom.xml

Email action plugin now packaged in the metrics ear.

Next version of HAM

---

docker-dist/pom.xml
docker-dist/src/main/docker/Dockerfile
docker-dist/src/main/docker/docker-assembly.xml
docker-dist/src/main/resources/standalone.conf

Also chown the dirs to jboss.
This later step may not be needed if the base image already does this.

Provide an explicit Dockerfile and modified standalone.conf.

---

openshift/startEphemeral.sh

This will allow to use the `startEphemeral.sh` script ootb

trivial: using the template as the url to github instead of local file

---

docker-dist/src/main/resources/ready.sh

the script is needed for the readiness probe in OpenShift and our OS template use it
Also the return code is now a bit mask denoting how many endpoints actually failed.

Removing the /inventory/status endpoint from the ready.sh script

---

hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/cache/BackfillCacheManager.java
hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/cache/InventoryHelper.java

- remove lookup of inventory service
- change avail metric filtering from using the metric type properties
(which are empty) to its assigned MetricDataType
- add Base64 decoding when stitching together the chunks

HAWKULAR-1212 Fix backfill

---

docker-dist/docker-compose-template.yml
docker-dist/pom.xml
docker-dist/src/main/docker/Dockerfile
docker-dist/src/main/resources/startcmd.sh
openshift/hawkular-services-ephemeral.yaml
openshift/hawkular-services-persistent.yaml
openshift/playbook.yaml

Just some minor improvements to the Docker and openshift stuff

Container improvements

---

hawkular-rest/hawkular-listener/pom.xml

Sync with latest hawkular-metrics

Upgrade rxjava 1.1.7 -> 1.2.9

---

pom.xml

Brings in line with hawkular-metrics 0.26.1.Final

Upgrade hawkular-alerts 1.6.0.Final -> 1.6.2.Final

---

docker-compose.yml

I think it's always a good point to provide a docker-compose file to quickly start any software :)

Provide docker-compose file at project root

---

docker-dist/src/main/resources/startcmd.sh

User on management realm seems to be required when deploying on openshift.
Fixes #172

HAWKULAR-1246 - Adds user and password to management realm

---

docker-dist/pom.xml
docker-dist/src/main/docker/docker-assembly.xml

- Fix warnings related to absolute path in docker assembly
- Update docker-maven-plugin to current version
- Remove some unnecessary deps

Minor improvements to docker build config

---

dist/src/main/resources/hawkular-welcome-content/index.html

Adds inventory status

---

hawkular-rest/hawkular-listener/pom.xml
hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/cache/BackfillCacheManager.java
hawkular-rest/pom.xml
itest/src/test/java/org/hawkular/services/rest/test/AgentITest.java
pom.xml

related to https://github.com/hawkular/hawkular-commons/pull/151 and https://github.com/hawkular/hawkular-commons/pull/154

Updated inventory model

---

dist/src/test/scripts/run-prometheus.sh
pom.xml

Change prometheus folder config

Bump srcdeps

---

docker-dist/src/main/docker/Dockerfile
docker-dist/src/main/resources/cert_utils.sh

@josejulio Could you please review?

Add possibility to specify SSL files location via parameters.

---

docker-dist/src/main/docker/Dockerfile
docker-dist/src/main/resources/cert_utils.sh

Add possibility to specify SSL public/private key path using parameters.

---

dist/src/test/scripts/run.sh

run.sh now supports start, stop, and status:
```
$ ./run.sh start
Starting containers...
7f34e3de9fa096131b44c99808a5783b3a1dcea399bb7e697450a483e782d328
63a15477c7cc885765df20f15b723e3f00ccaebdb9bd3279c5ea4c57a5aea503
$ ./run.sh status
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
63a15477c7cc        prom/prometheus:v2.0.0                     "/bin/prometheus --co"   4 seconds ago       Up 3 seconds                            high_easley
7f34e3de9fa0        hawkular/hawkular-services:hawkular-1275   "/bin/sh -c /opt/hawk"   4 seconds ago       Up 3 seconds                            distracted_engelbart
]$ ./run.sh stop
Stopping containers...
63a15477c7cc
7f34e3de9fa0
```

add stop and status to what the run script can do.

---

pom.xml

Bump agent and commons srcdeps

---

hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/MIQEventUtils.java

Middleware Provider Timelines Events - Add EAP Host Name to Event Details

Bug 1424627 

---

pom.xml

Bump agent

---

pom.xml

Bump commons and agent

---

pom.xml

Bump agent and commons
