hawkular/hawkular-services

- RUNNING.adoc
- feature-pack/pom.xml
- feature-pack/src/main/xsl/configuration/standalone/hawkular-services-template.xsl
This reintroduces the ability to build Hawkular Services with Embedded Cassandra.
You can do this via -Pembeddedc Maven profile.
This feature allows an easier "on ramp" for you developers or folks that want to demo - no need to install and start a separate Cassandra server (no need to even know that you have to do it).
> put embedded cassandra in hawkular services if built with embeddedc profile

- dist/pom.xml
Minor improvement to the dev build:
`mvn clean install -DskipTests` => `[INFO] Total time: 19.695 s`
`mvn clean install -DskipTests -Pdev` => `[INFO] Total time: 6.146 s`
Before this change the times were nearly the same, because the archives were created all the time.
It's done the same way as in `hawkular/hawkular`
> Do not build the zip and tar.gz if the 'dev' Maven profile is activated

- hawkular-rest/hawkular-rest-api/src/main/java/org/hawkular/rest/api/v1/impl/RestURLImpl.java
- hawkular-rest/hawkular-rx/src/main/java/org/hawkular/rx/commands/common/HawkularConfiguration.java
- hawkular-rest/hawkular-rx/src/main/java/org/hawkular/rx/httpclient/OkClient.java
MiQ ruby client calls this during the tests - https://github.com/hawkular/hawkular-client-ruby/blob/master/spec/integration/inventory_spec.rb#L92:L102
@lucasponce could you please review? This is one of the reasons why the specs were failing against the live services.
> Adding hawkular-tenant headers for the URL rest api. 

- docker-dist/src/main/resources/startcmd.sh
The hostname command is not always available, specifically in a RHEL 7 container
> Use $HOSTNAME instead of `hostname` command

- docker-dist/pom.xml
- docker-dist/src/main/docker/docker-assembly.xml
The profile is off by default.  When activated it creates a zip
of the hawkular files which can be added to a wildfly or eap instance.
This is useful in case you have a separate docker build and you want just the
hawkular files to layer onto wildfly/eap.
> Add Maven profile to the docker dist module which creates zip

- itest/src/test/java/org/hawkular/services/rest/test/MetricsAlertingITest.java
- pom.xml
This PR needs a release of metrics and alerting.
The bug on the itest masked some issues on the intregation side.
I will update the PR once these releases are out.
Please don't merge as pom.xml is provisional.
> HAWKULAR-1121 Fix wrong path on MetricsAlerting itest

- feature-pack/feature-pack-build.xml
- feature-pack/pom.xml
- feature-pack/src/main/xsl/configuration/standalone/hawkular-services-subsystems.xsl
- itest/src/test/java/org/hawkular/services/rest/test/AgentITest.java
- pom.xml
These two should work well together and let the services itests pass.
Modify the build to include the datasources and jdbc drivers from the inventory feature-pack.
> Bump to inventory 0.19.2.Final and agent to 0.22.0.Final.

- .travis.hawkular-client.ruby.sh
- .travis.install.maven.sh
- .travis.yml
Added testing of hawkular-client-ruby on every hawkular-services PR.
To so I had to drop some .travis.yml features (Disabled container-based infrastructure) and installing maven by hand (the script is borrowed from other hawkular projects).
The testing of hawkular-client-ruby shouldn't affect the hawkular-services test itself, as is on an after_success. It would only fail if the build stalled for some reason see [this](https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build) for more info.
See [here](https://github.com/josejulio/hawkular-services/pull/1) for an example of how it would report errors on the hawkular-client-ruby.
> After succesfully testing, try to test hawkular-client-ruby.

- pom.xml
I forgot to include the hsqldb memory consumption settings in `1.0.1.Final`. Mea culpa :disappointed: .
`1.0.2.Final` fixes that (and just that) but I guess it is too late for this week's services. Sorry for that..
> Bump inventory to 1.0.2.Final.

- docker-dist/README.adoc
- docker-dist/src/main/resources/startcmd.sh
By default it creates ~500 threads so lets reduce that number to 30. I haven't experienced any perf drop by smoke testing.
more info here:
https://developer.jboss.org/thread/268397
> ActiveMQ isn't able to create another thread when running in docker.

- docker-dist/src/main/docker/docker-assembly.xml
- docker-dist/src/main/resources/ready.sh
It curls all the /{component}/status e…ndpoints and if all of them are ok, returns 0
If we use this instead of simple [httpGet -> /status](https://github.com/hawkular/hawkular-services/pull/115/files#diff-a37849aeb4d4e33017d0dc579b6231b3R127), it should solve the issue with slow C* start where some components were initialized and come were not.
If some service is not ok, the whole pod would be considered as not ok and killed. In case of slow C*, the next attempt would be successful.
> Adding a simple readiness bash script

- docker-dist/src/main/docker/Dockerfile
- docker-dist/src/main/resources/startcmd.sh
Although, the ownership of the mounted volume should be preserved from the host machine. 
I.E.
```bash
mkdir /tmp/foo && sudo chown nfsnobody:nfsnobody /tmp/foo
```
and then running..
```bash
docker run -v /tmp/foo:/opt/data ${USER}/hawkular-services:0.34.0.Final-SNAPSHOT ls -ld /opt/data
```
it should return something like 
`drwxrwxr-x. 2 65534 65534 40 Mar  3 14:46 /opt/data`
(65534 ~ nfsnobody)
If the explicit volume mapping with `-v` switch is not used (or in the docker-compose.yaml file the volume mapping is not specified), then the `/opt/data` is owned by the root and the jboss user can't write the log files to it. This PR fixes this implicit case when running the container w/o the explicit volume mapping, so that:
```bash
docker run ${USER}/hawkular-services:0.34.0.Final-SNAPSHOT …
```
> Make the /opt/data writable by jboss:jboss

- openshift/README.adoc
- openshift/hawkular-services-ansible-vars.yaml
- openshift/hawkular-services-ephemeral.yaml
- openshift/hawkular-services-persistent.yaml
- openshift/playbook.yaml
- openshift/startEphemeral.sh
With this PR the openshift template generates the username and password for hawkular-services container and passes it as env. variables. Further improvement would be using the openshift secrets for that and read it by the h-services image as files, but I guess we would need a wrapper openshift image for that, because it's too openshift/k8s specific and it shouldn't be in the generic docker image that can be run also in the docker-compose context or plain with the '--link magic'.
It's still possible to pass the username or password as a parameter:
* for ephemeral:
```bash
[HAWKULAR_USER=jdoe] [HAWKULAR_PASSWORD=jdoe] TEMPLATE="./hawkular-services-ephemeral.yaml" ./startEphemeral.sh
```
* for persistent:
```bash
ansible-playbook playbook.yaml --ask-sudo-pass --extra-vars …
```
> Template credentials auto-generation

- docker-dist/README.adoc
- docker-dist/src/main/docker/Dockerfile
- docker-dist/src/main/docker/docker-assembly.xml
- docker-dist/src/main/resources/cert_utils.sh
- docker-dist/src/main/resources/startcmd.sh
- feature-pack/feature-pack-build.xml
- feature-pack/pom.xml
- feature-pack/src/main/xsl/configuration/standalone/hawkular-services-subsystems-ssl.xsl
- feature-pack/src/main/xsl/configuration/standalone/hawkular-services-template-ssl.xsl
- feature-pack/src/main/xsl/subsystem-templates/hawkular-services-undertow-ssl.xsl
- feature-pack/src/main/xsl/subsystem-templates/hawkular-wildfly-agent-ssl.xsl
It also adds the way to pass the credentials as files that can be mounted (~ OpenShift secrets)
There are 3 ways to enable the ssl, each of them assumes the `HAWKULAR_USE_SSL` env variable is set to true:
* The fist method is using the private and public key provided as files located on `/client-secrets/hawkular-services-private.key` and `/client-secrets/hawkular-services-public.pem`
* The second method is via 1 pkcs12 file containing both keys located on `/client-secrets/hawkular-services.pkcs12`
* And the last method is to auto-generate the self-signed certificate for localhost (or perhaps even for a given hostname) by not creating the files described above, but still setting the `HAWKULAR_USE_SSL`.
There are also changes to the `feature-pack` maven module in order to generate the …
> [HAWKULAR-1200] - SSL support for hawkular-services docker image

- hawkular-rest/hawkular-listener/pom.xml
- hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/cache/InventoryHelper.java
- hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/exception/InvalidInventoryChunksException.java
- hawkular-rest/hawkular-listener/src/test/java/org/hawkular/listener/cache/InventoryHelperTest.java
- pom.xml
- Adding unit tests on inventory
- Adding sanity checks on chunks reading; mazz had a case where data was not being read correctly, I'm not actually sure if data was somehow corrupted or if it was race condition when writing to C* and reading at the same time, thus reading incomplete data.
@jshaughn I've added some log.warn here, when such sanity check fails. Is "warn" the correct level to put here? Hopefully we shouldn't see it regularly; or if we do then we have a problem.
> Inventory sanity checks

- openshift/hawkular-services-ephemeral.yaml
- openshift/hawkular-services-persistent.yaml
with this change I am able to set-up the oc cluster w/ hawkular-services under 2 minutes
before:
start at 16:36:18
ready at 16:38:57
=> 00:02:39
after the change:
start at 16:39:55
ready at 16:41:22
=> 00:01:27
so from 159 seconds it's reduced to 87 seconds on my laptop
> [HAWKULAR-1217] Reducing the waiting times for the very first readiness check.

- docker-dist/src/main/docker/Dockerfile
`$JAVA_HOME/jre/lib/security/cacerts` can be a symlink, thus we need to resolve the real path to change the permissions to that file.
> [BZ-1455877] Resolve real path for cacerts before setting permissions

- pom.xml
Hi Guys.
I am sending this PR to update a minor release on Hawkular Alerts and Hawkular Metrics.
It contemplates a bug fix for hawkular alerts when tag queries may cause cause a BusyPoolDriverException on Cassandra (See more on https://issues.jboss.org/projects/HWKALERTS/issues/HWKALERTS-275)
> Minor Update on Hawkular Metrics and Alerts Version

- hawkular-rest/hawkular-listener/src/main/java/org/hawkular/listener/bus/CommandEventListener.java
Add events into the command gateway so they are  visible to ManageIQ
Related to: https://github.com/ManageIQ/manageiq-providers-hawkular/pull/71
> Add JDBC events for ManageIQ into command gateway

- docker-dist/src/main/docker/Dockerfile
Wildlfy relies on using file permissions to determine if a local connection to DMR should be authorized or not (if the user permission to create ${JBOSS_HOME}/tmp and create a file there, they can be authenticated).
Since OpenShift runs the container as a user from a range (by default) we need to allow any user to create the file required for a local DMR connection. This will allow the agent to monitor the Hawkular Services instance.
> HAWKULAR-1319: all the agent to connect to wildfly in our docker image

- openshift/hawkular-services-ephemeral.yaml
- openshift/hawkular-services-persistent-ssl.yaml
- openshift/hawkular-services-persistent.yaml
If we set the pull policy to 'IfNotPresent' then it means if we will never update our image (which is problematic if you are using 'latest' since it wont actually download a newer image)
The better option is to usually not set the 'ImagePullPolicy' directly. If the image is 'latest' it will automatically set the 'ImagePullPolicy' to 'Always'. Otherwise it will use 'IfNotPresent'
> HAWKULAR-1315: remove ImagePullPolicy from templates and use defaults

- feature-pack-parent/feature-pack/src/main/xsl/subsystem-templates/hawkular-services-infinispan.xsl
- feature-pack-parent/feature-pack/src/main/xsl/subsystem-templates/hawkular-services-messaging-activemq.xsl
Alerting 1.8 manages configuration outside standalone.xml, so those caches are redundant and creates noise also in agent.
Also removing unused destinations, we don't communicate alerting through the bus.
> Remove unused Caches and Destinations from config

- dist/pom.xml
- pom.xml
If the "dev" profile is activated, generation of the hawkular services
dist zip is skipped to speed up the build.  The itest and docker-dist
modules are dependent on this zip, so the build will fail if the zip
is not in the local maven repo.  This change causes the itest and
docker-dist modules to be skipped completely if the "dev" profile is active.
> HAWKULAR-1336 - configure build to fix issue with dev profile

- docker-dist/src/main/docker/docker-assembly.xml
- docker-dist/src/main/resources/cert_utils.sh
- feature-pack/feature-pack-build.xml
- feature-pack/pom.xml
- feature-pack/src/main/xsl/configuration/standalone/hawkular-services-template-docker-ssl.xsl
There are some cases when I don't have control of the certificates and can't add localhost SANs, an example is when I use OpenShift Service Serving Certificate Secrets.
I think is safe to not use SSL for this case, even if the SSL is enabled. because all traffic is inside the container, which has the private/public keys of the SSL encryption.
This is just for the case when HAWKULAR_SSL=true, so the other way of seeing this is PR is "setting up the SSL but making sure that agent inside the container still use plain HTTP)
> Avoiding SSL usage for the agent inside container

- openshift/hawkular-services-ephemeral.yaml
- openshift/hawkular-services-persistent.yaml
This PR increases the timeout of liveness probe and readiness probe in order to avoid the following exception:
` org.jboss.resteasy.spi.UnhandledException: RESTEASY003770: Response is committed, can't handle exception connection reset by peer` 
This exception happens because the timeout is too small and the request takes time under some conditions and the probe interrupts the request.
> Increase the liveness and readiness probes timeout

- itest/src/test/java/org/hawkular/services/rest/test/AgentITest.java
This is to set Hawkular Services in a good state.
Once, agent is updated and server is in "running" state again, this test will fail and we will update the result.
> HAWKULAR-1347 Fix AgentITest assert result
